baseURL = ""
languageCode = "en-us"
title = "Daryl Galvez"
theme = "m10c"
paginate = 5


[params]
  author = "Daryl Galvez"
  description = "My personal website and blog"
  [[params.social]]
    name = "github"
    url = "https://github.com/darylkevin"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/daryl-galvez/"
  [[params.social]]
    name = "file-text"
    url = ""
  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
