---
title: "Happy New Year"
date: 2021-01-01T00:00:00+08:00
draft: false
author: "Daryl Galvez"
description: ""
slug: ""
tags: ["2021", "new year"]
categories: []
externalLink: ""
series: []
---

** Happy New Year!

Hi!

Hope you are all doing well for the past few months. The past year was really a rough one for most of us.
I was not able to put much content on my webpage as I was busy with a lot of things like most of you as well.
Yet here we are. Still going strong and hopeful. Whatever this year might bring, let's all be here for each other,
make the most of what we have, and make the world a slightly better place than what is was yesterday.

** Going forward!
I plan to churn out content every now and then and use this website to document my learnings. Sort of like a blog.
I would still like to focus on the technical things and maybe use this as a resource and notes for me going forward,
and maybe use this as practice to organize my thoughts and improve my writing skills.

I still have difficulty as you can see here and I'll strive to improve.

I'm looking forward to having all of you with me on this journey.

See you!
